$schema: https://unpkg.com/release-it@20/schema/release-it.json
git:
  commit: true
  commitMessage: "chore: release v${version}"
  tag: true
  tagName: "v${version}"
  push: true
github:
  release: true
npm:
  publish: true
  publishPackageManager: pnpm
  skipChecks: true
hooks:
  "before:init":
    - pnpm lint
  "after:bump":
    - pnpm fmt
    - pnpm build
plugins:
  "@release-it/conventional-changelog":
    preset:
      name: conventionalcommits
    infile: CHANGELOG.md
